apiVersion: v1
kind: Pod
metadata:
  name: ubuntutest
  namespace: default
spec:
  # hostNetwork: true
  containers:
  - name: ubuntutest
    image: ubuntu:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
